# DEBUG: True

BASE_LOG_DIR: results/26-03-20
EXPERIMENT_SUFFIX:
OVERWRITE_LOG_DIR: false

LARGE_BATCH: 128  # batch for fwd-bkwd pass
SMALL_BATCH: 128  # batch for one forward pass
BASE_LR: 0.1
EPOCHS: 50 # 100
VAL_STEP: 25000
USE_TTA_EVAL: false

model:
  type: tiny # ResNet18_kuangliu

opt:
  type: SGD
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0005
  # SELECTION_METHOD: 'tvalue2'
  # LR_GROW: 0.01
  # LR_SHRINK: 0.01

scheduler:
  type: CosineAnnealingLR # <None> CosineAnnealingLR LinearLR
  LR_MIN: 0.001
  BY_EPOCH: true

LABEL_SMOOTH: 0 #.2 # .01
CLIP_PROB:
  ENABLED: false
  LEVEL: 0.2 # If not None, clip loss between CLIP_LEVEL and 1-CLIP_LEVEL/num_classes

CLIP_LOSS:
  ENABLED: false
  LOW_THRESHOLD: 0.5
  HIGH_THRESHOLD: 1.0
  START_EPOCH: 10  # cout from 0, so the same as skip epochs